<a href="https://colab.research.google.com/github/perurianusha/Python_Libraries/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b=np.array([[9,5,6,3,4],[6,8,9,0,3]])
print(b)

[[9 5 6 3 4]
 [6 8 9 0 3]]


In [ ]:
#get dimension
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
#get shape
print(a.shape) # row ,col
print(b.shape)

(3,)
(2, 5)


In [ ]:
#get type
print(a.dtype)
print(b.dtype)


int64
int64


In [ ]:
#get size
print(a.itemsize)
print(b.itemsize)
#size
print(a.size)
print(b.size)

8
8
3
10


In [ ]:
#get total size
print(a.itemsize*a.size)
print(b.itemsize*b.size)

24
80


In [ ]:
#accessing/changing specific elenents rows and columns


In [ ]:
s=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(s.shape)

(2, 7)


In [ ]:
print(s[:])

#get a specific row
print(s[0])  # 0 row
print(s[0,:])
print(s[0,1:4])


#get a specific column
print(s[:,2]) # 2 column
print(s[:,6])
print(s[:,0])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[2 3 4]
[ 3 10]
[ 7 14]
[1 8]


In [ ]:
#get a specific element [r,c]
print(s[1,-2]) # row,  0,1,2,3....-3,-2,-1
print(s[1,5])
print(s[0,-1])

13
13
7


In [ ]:
#[row,start:end:stepsize]
print(s[0,1:-1:2])
print(s[1,1:-1:2])

[2 4 6]
[ 9 11 13]


In [ ]:
#change

s[1,5]=20
s[0,5]=21
print(s[0])
print(s[1])

s[: , 2]=[99,98]
print(s)

[ 1  2  3  4  5 21  7]
[ 8  9 10 11 12 20 14]
[[ 1  2 99  4  5 21  7]
 [ 8  9 98 11 12 20 14]]


In [ ]:
#3-d examples

m=np.array([[[1,2],[3,4]],[[9,8],[7,6]]])
print(m)


[[[1 2]
  [3 4]]

 [[9 8]
  [7 6]]]


In [ ]:
#row element /elements
print(m[0,1,:])
print(m[0,1,1])

print(m[1,0,:])
print(m[1,0,0])

print(m[:,0,:])
print(m[:,1,:])

#column
print(m[:,0,1])
print(m[:,1,0])



[3 4]
4
[9 8]
9
[[1 2]
 [9 8]]
[[3 4]
 [7 6]]
[2 8]
[3 7]


In [ ]:
m[:,1,:]=[[0,5],[0,0]]
print(m)

[[[1 2]
  [0 5]]

 [[9 8]
  [0 0]]]


In [ ]:
m[:,1,0]=[12,13]
m

array([[[ 1,  2],
        [12,  5]],

       [[ 9,  8],
        [13,  0]]])

In [ ]:
#initializing different types of arrays
#all os matrix

print(np.zeros((2,3)))
print("\n")
print(np.zeros((2,3,3)))
print("\n")
print(np.ones((2,3)))
print("\n")
print(np.ones((2,3,3)))


print("\n")
print(np.full((2,3),9))

print("\n")
print(np.full(a,9))

#random decimal numbers
print("\n")
np.random.rand(4,2)

#random interger numbers
print("\n")
np.random.randint(7,size=(3,3))#in

#random decimal numbers
print("\n")
np.random.random_sample(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]]


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


[[1. 1. 1.]
 [1. 1. 1.]]


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


[[9 9 9]
 [9 9 9]]


[[[9 9 9]
  [9 9 9]]]








array([0.47630407, 0.86620122, 0.5121171 ])

In [ ]:
np.random.randint(3,7,size=(3,3))#7not included #include

array([[6, 6, 5],
       [3, 5, 3],
       [4, 5, 4]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# 1d
arr=np.array([1,2,3,])
r=np.repeat(arr,3,axis=0)
print(r)

[1 1 1 2 2 2 3 3 3]


In [ ]:
# 2d
arr=np.array([[1,2,3,]])
r=np.repeat(arr,3,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
hw=np.ones((5,5))
print(hw)
hw[1,1:4]=[0,0,0]
hw[3,1:4]=[0,0,0]
hw[2,1]=0
hw[2,-2]=0
hw[2,2]=9
hw

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
o1=np.ones((5,5))
print(o1)

o2=np.zeros((3,3))
o2[1,1]=9
print(o2)

print(o1[1:-1,1:-1])#1st row to the 4th row(1:4)....1st col to the 4th col(1:4)

o1[1:4,1:4]=o2

print(o1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#be carful while copying
a=np.array([1,2,3])
b=a
b[0]=100
print(a)


a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)
print(a)

[100   2   3]
[100   2   3]
[1 2 3]


In [ ]:
z=np.array([1,2,3,4])
k=np.array([9,8,7,6])
print(z+2)
print(z-2)
print(z*2)
print(z/2)
print(z+k)

print(np.cos(z))

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[10 10 10 10]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [ ]:
#linear algebra

a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
#determinant
c=np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
#statistics

st=np.array([[1,2,3],[4,5,6]])
print(st)
print(np.min(st))
print(np.max(st))
print(np.sum(st))


print(np.min(st,axis=0))#row axis=0 min row
print(np.max(st,axis=1))#col axis=1 max col
print(np.sum(st,axis=1))

[[1 2 3]
 [4 5 6]]
1
6
21
[1 2 3]
[3 6]
[ 6 15]


In [ ]:
#reorganizing arrays

t=np.array([[1,2,3],[4,5,6]])
print(t)

tf=t.reshape((6,1))
print(tf)



[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
#vertically stacking vectors

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#horizonal stacking vectors

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#miscellaneous

#load data from file

f=np.genfromtxt('/data.txt',delimiter=',')
f=f.astype('int32')
print(f)

FileNotFoundError: ignored

In [ ]:
#boolean masking andadvanced indexing
f>50

In [ ]:
print(np.any(f>50,axis=1))
print(np.any(f>50,axis=0))

In [ ]:
(~((f>50) & (f<100)))

In [ ]:
(((f>50) & (f<100)))

In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

In [ ]:
ex1=np.array([1,2,3,4])
ex1


array([1, 2, 3, 4])

In [ ]:
ex2=np.ones([4,2])
print(ex2.shape)
print(ex2)

(4, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
ex3=ex2.reshape((2,4))
print(ex3.shape)
print(ex3)

(2, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Slicing to extract a subarray
subarray = arr[1:4]  # Get elements from index 1 to index 3
print(subarray)     # Output: [2 3 4]

[2 3 4]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Accessing individual elements using indexing
print(arr[0])  # Output: 1
print(arr[2])  # Output: 3

1
3


In [ ]:
a=np.array([[2,4],[5,3]])
print(a)
b=np.array([[6,4],[1,2]])
print(b)

print(np.multiply(a,b))
print(a*b)

[[2 4]
 [5 3]]
[[6 4]
 [1 2]]
[[12 16]
 [ 5  6]]
[[12 16]
 [ 5  6]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(max(arr1))
print(sum(arr1))
print(np.sqrt(arr1))
print(arr1*2)

result = np.multiply(arr1, arr2)
print(result)
print(arr1*arr2)

3
6
[1.         1.41421356 1.73205081]
[2 4 6]
[ 4 10 18]
[ 4 10 18]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 2])

result = arr1 == arr2
print(result)

[False  True False]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1)
print(arr2)

result = np.concatenate((arr1, arr2), axis=0) #row #vertical
print(result)

result = np.concatenate((arr1, arr2), axis=1) # col #horizontal
print(result)


print(np.vstack((arr1,arr2))) #vertical
print(np.hstack((arr1,arr2))) #horizontal

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.matmul(matrix1, matrix2)
print(result)

[[19 22]
 [43 50]]


In [ ]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = matrix1 @ matrix2
print(result)

[[19 22]
 [43 50]]


In [ ]:
a=np.array([1,2,3,4])

print(np.mean(a))
print(np.median(a))
print(np.std(a))

2.5
2.5
1.118033988749895


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
condition = arr > 3
filtered_arr = arr[condition]
print(filtered_arr)

[4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (2, 3))
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

random_numbers = np.random.normal(loc=0, scale=1, size=10)
print(random_numbers)

[-0.3899493  -0.77084837 -0.53721578 -0.90545317  1.44793347 -1.15491711
 -1.13672695  0.69553436  0.76337825  0.3191943 ]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
np.save('array.npy', arr)

loaded_arr = np.load('array.npy')
print(loaded_arr)


[1 2 3 4 5]
